spring.application.name=IntelliMart

# DB config
spring.datasource.url=jdbc:mysql://localhost:3306/intellimart?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Path Matching
spring.mvc.pathmatch.matching-strategy=path-pattern-parser

# Image serving
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.mvc.static-path-pattern=/uploads/**

# JWT Configuration
jwt.secret=InteliMart_Project_Secret_Key_2026_Secure_And_Long
jwt.expiration.time=86400000

# RazorPay
razorpay.key.id=rzp_test_SBDo89UP0tFzEp
razorpay.key.secret=OukbgBFE1c1wTa2D3NoqYHnM
# Cloudinary
cloudinary.cloud-name=dwdbx72db
cloudinary.api-key=648251253545279
cloudinary.api-secret=lxWKaDhFcpEtbKAy8wJEbB_-aR0

# File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB