spring.application.name=IntelliMart

# DB config
spring.datasource.url=jdbc:mysql://localhost:3306/intellimart?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Path Matching
spring.mvc.pathmatch.matching-strategy=path-pattern-parser

# Image serving (if you store images locally)
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.mvc.static-path-pattern=/uploads/**

# JWT Configuration
jwt.secret=InteliMart_Project_Secret_Key_2026_Secure_And_Long
jwt.expiration.time=86400000
